In [1]:
import pandas as pd

In [2]:
# Load VDAB data
vdab_file_path = 'C:/Users/Cool_/Documents/GitHub/PPA/hr_tool_irakli/vdab_categories_provinces.csv'
vdab_jobs = pd.read_csv(vdab_file_path)

In [3]:
vdab_jobs

,Unnamed: 0.1,Unnamed: 0,url,title,employer,location,description,description_translated,title_translated,keywords,top_categories,province
0,0,0,https://www.vdab.be/vindeenjob/vacatures/68793122,technisch aankoopassistent,le grand & associates,kortrijk,Functieomschrijving LGA Engineering is een rek...,Job description LGA Engineering is a recruitme...,technical purchasing assistant,"{'Profile Profile Experience', 'recruitment', ...","['Administration', 'Sales', 'Logistics, transp...",West Flanders
1,1,1,https://www.vdab.be/vindeenjob/vacatures/68793123,pricing analist,lga engineering,provincie vlaams-brabant,Functieomschrijving Heb jij een passie voor de...,Job description Do you have a passion for the ...,pricing analist,"{'Job', 'career', 'job', 'competencies', 'logi...","['Sales', 'Administration', 'Creative jobs']",Flemish Brabant
2,2,2,https://www.vdab.be/vindeenjob/vacatures/68793124,pricing analist maritiem,lga engineering,antwerpen,Functieomschrijving Voor onze logistieke klant...,Job description For our logistics customer in ...,maritime pricing analyst,"{'Job', 'Offer Offer', 'contract prices', 'Ana...","['Administration', 'Sales', 'Logistics, transp...",Antwerp
3,3,3,https://www.vdab.be/vindeenjob/vacatures/68793125,warehouse teamleader,start people,herentals,Functieomschrijving Onze klant gevestigd in He...,Job description Our client based in Herentals ...,warehouse team leader,"{'operating logistics', 'role', 'globally oper...","['Administration', 'Logistics, transport & pur...",Antwerp
4,4,4,https://www.vdab.be/vindeenjob/vacatures/68793126,grafisch vormgever,start people,pelt,Functieomschrijving 1 op de 10 gezinnen geniet...,Job description 1 in 10 families already enjoy...,graphical designer,"{'Job', 'designing', 'wooden windows', 'doors'...","['Administration', 'Sales', 'Creative jobs']",Limburg
...,...,...,...,...,...,...,...,...,...,...,...,...
11122,11122,11122,https://www.vdab.be/vindeenjob/vacatures/68804504,plaatser - glazen binnenwanden,forum construct maldegem,oostkamp,Functieomschrijving Voor onze klant zijn wij o...,Job description We are looking for an installe...,installer - glass interior walls,"{'glass', 'West Flanders region', 'GLASS INTER...","['Administration', 'Logistics, transport & pur...",West Flanders
11123,11123,11123,https://www.vdab.be/vindeenjob/vacatures/68804505,heftruckchauffeur,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als heftruckchauffeur sta ...,Job description As a forklift driver you are r...,forklift driver,"{'equipment', '3rd grade', 'deviations Report ...","['Administration', 'Logistics, transport & pur...",West Flanders
11124,11124,11124,https://www.vdab.be/vindeenjob/vacatures/68804506,technisch coördinator (+ bedrijfswagen),square city,evergem,Functieomschrijving Verwacht het onverwachte v...,Job description Expect the unexpected for your...,technical coordinator (+ company car),"{'Technical', 'maintenance', 'supervise', 'res...","['Administration', 'Sales', 'Logistics, transp...",East Flanders
11125,11125,11125,https://www.vdab.be/vindeenjob/vacatures/68804507,mechanieker,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als mechanieker behoort to...,"Job description As a mechanic, your duties inc...",mechanic,"{'equipment', 'mechanical pieces', 'maintenanc...","['Logistics, transport & purchase', 'Administr...",West Flanders
11126,11126,11126,https://www.vdab.be/vindeenjob/vacatures/68804508,kraanmachinist,vivaldis construct,harelbeke,Functieomschrijving Voor onze klant te Harelbe...,Job description For our customer in Harelbeke;...,crane operator,"{'TYRE CRANE OPERATOR', 'TYPE CRANE', 'TYRE', ...","['Administration', 'Sales', 'Creative jobs']",West Flanders

In [16]:
import re

# Function to classify the job as starter or experienced
def classify_job(description, title):
    description = description.lower()
    title = title.lower()
    
    starter_keywords = ['no experience required', 'junior', 'entry-level', 'starter', 'graduate', 'young']
    experienced_keywords = ['years of experience', 'senior', 'experienced', 'minimal', 'at least', 'no less than']
    
    for keyword in starter_keywords:
        if re.search(keyword, description) or re.search(keyword, title):
            return 'starter'
    
    for keyword in experienced_keywords:
        if re.search(keyword, description) or re.search(keyword, title):
            return 'experienced'
    
    return 'experienced'  # Default to experienced if no keywords are found

# Apply the function to the translated description
vdab_jobs['job_level'] = vdab_jobs.apply(lambda x: classify_job(x['description_translated'], x['title_translated']), axis=1)

# Display the updated dataframe
vdab_jobs

,Unnamed: 0.1,Unnamed: 0,url,title,employer,location,description,description_translated,title_translated,keywords,top_categories,province,job_level
0,0,0,https://www.vdab.be/vindeenjob/vacatures/68793122,technisch aankoopassistent,le grand & associates,kortrijk,Functieomschrijving LGA Engineering is een rek...,Job description LGA Engineering is a recruitme...,technical purchasing assistant,"{'Profile Profile Experience', 'recruitment', ...","['Administration', 'Sales', 'Logistics, transp...",West Flanders,experienced
1,1,1,https://www.vdab.be/vindeenjob/vacatures/68793123,pricing analist,lga engineering,provincie vlaams-brabant,Functieomschrijving Heb jij een passie voor de...,Job description Do you have a passion for the ...,pricing analist,"{'Job', 'career', 'job', 'competencies', 'logi...","['Sales', 'Administration', 'Creative jobs']",Flemish Brabant,experienced
2,2,2,https://www.vdab.be/vindeenjob/vacatures/68793124,pricing analist maritiem,lga engineering,antwerpen,Functieomschrijving Voor onze logistieke klant...,Job description For our logistics customer in ...,maritime pricing analyst,"{'Job', 'Offer Offer', 'contract prices', 'Ana...","['Administration', 'Sales', 'Logistics, transp...",Antwerp,experienced
3,3,3,https://www.vdab.be/vindeenjob/vacatures/68793125,warehouse teamleader,start people,herentals,Functieomschrijving Onze klant gevestigd in He...,Job description Our client based in Herentals ...,warehouse team leader,"{'operating logistics', 'role', 'globally oper...","['Administration', 'Logistics, transport & pur...",Antwerp,experienced
4,4,4,https://www.vdab.be/vindeenjob/vacatures/68793126,grafisch vormgever,start people,pelt,Functieomschrijving 1 op de 10 gezinnen geniet...,Job description 1 in 10 families already enjoy...,graphical designer,"{'Job', 'designing', 'wooden windows', 'doors'...","['Administration', 'Sales', 'Creative jobs']",Limburg,experienced
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,11122,11122,https://www.vdab.be/vindeenjob/vacatures/68804504,plaatser - glazen binnenwanden,forum construct maldegem,oostkamp,Functieomschrijving Voor onze klant zijn wij o...,Job description We are looking for an installe...,installer - glass interior walls,"{'glass', 'West Flanders region', 'GLASS INTER...","['Administration', 'Logistics, transport & pur...",West Flanders,experienced
11123,11123,11123,https://www.vdab.be/vindeenjob/vacatures/68804505,heftruckchauffeur,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als heftruckchauffeur sta ...,Job description As a forklift driver you are r...,forklift driver,"{'equipment', '3rd grade', 'deviations Report ...","['Administration', 'Logistics, transport & pur...",West Flanders,experienced
11124,11124,11124,https://www.vdab.be/vindeenjob/vacatures/68804506,technisch coördinator (+ bedrijfswagen),square city,evergem,Functieomschrijving Verwacht het onverwachte v...,Job description Expect the unexpected for your...,technical coordinator (+ company car),"{'Technical', 'maintenance', 'supervise', 'res...","['Administration', 'Sales', 'Logistics, transp...",East Flanders,starter
11125,11125,11125,https://www.vdab.be/vindeenjob/vacatures/68804507,mechanieker,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als mechanieker behoort to...,"Job description As a mechanic, your duties inc...",mechanic,"{'equipment', 'mechanical pieces', 'maintenanc...","['Logistics, transport & purchase', 'Administr...",West Flanders,experienced
11126,11126,11126,https://www.vdab.be/vindeenjob/vacatures/68804508,kraanmachinist,vivaldis construct,harelbeke,Functieomschrijving Voor onze klant te Harelbe...,Job description For our customer in Harelbeke;...,crane operator,"{'TYRE CRANE OPERATOR', 'TYPE CRANE', 'TYRE', ...","['Administration', 'Sales', 'Creative jobs']",West Flanders,experienced

In [17]:
vdab_jobs["job_level"].value_counts()

experienced    9815
starter        1312
Name: job_level, dtype: int64

In [18]:
vdab_jobs.to_csv('C:/Users/Cool_/Documents/GitHub/PPA/hr_tool_irakli/VDAB_categories_provinces_level.csv', index=False)

In [21]:
# Display the descriptions of jobs classified as 'starter'
starter_jobs = vdab_jobs[vdab_jobs['job_level'] == 'starter'][['title', 'job_level']]
starter_jobs

                                                   title job_level
23     payroll advisor - bedrijfswagen & hippe ondern...   starter
27                                            technieker   starter
38                                           elektricien   starter
42     accountant / boekhouder - bonussysteem en bedr...   starter
43          audit manager - klaar voor de volgende stap?   starter
...                                                  ...       ...
11087                    logistiek medewerker poetsploeg   starter
11093                          werfleider middenspanning   starter
11105                 quality control specialist voeding   starter
11107                                    tekenaar (gent)   starter
11124            technisch coördinator (+ bedrijfswagen)   starter

[1261 rows x 2 columns]